void currency_convertor_pro(int s,int d)
{float  i,o;
	if((s==1)&&(d==1))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i;
		printf("\noutput=%f",o);
	}
	if((s==1)&&(d==2))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=(float)(i/65);
		printf("\noutput=%f",o);
	}
	if((s==1)&&(d==3))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=(i*1.76);
		printf("\noutput=%f",o);
	}
	if((s==1)&&(d==4))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=(i/75);
		printf("\noutput=%f",o);
	}
	if((s==1)&&(d==5))
	{
		printf("\nenter input:-");
		scanf("\n%f",&i);
		o=i/8.3;
		printf("\noutput=%f",o);
	}
	if((s==1)&&(d==6))
	{
		printf("\nenter input:-");
		scanf("\n%f",&i);
		o=i/50;
		printf("\noutput=%f",o);
	}
	if((s==1)&&(d==7))
	{
		printf("\nenter input:-");
		scanf("\n%f",&i);
		o=i/44.6;
		printf("\noutput=%f",o);
	}
	if((s==1)&&(d==8))
	{
		printf("\nenter input:-");
		scanf("\n%f",&i);
		o=i/9.75;
		printf("\noutput=%f",o);
	}
	if((s==2)&&(d==1))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=(i*65);
		printf("\noutput=%f",o);
	}
	if((s==2)&&(d==2))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i;
		printf("\noutput=%f",o);
	}
	if((s==2)&&(d==3))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i*114;
		printf("\noutput=%f",o);
	}
	if((s==2)&&(d==4))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i/1.6;
		printf("\noutput=%f",o);
	}
	if((s==2)&&(d==5))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i*7.8;
		printf("\noutput=%f",o);
	}
	if((s==2)&&(d==6))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i*1.3;
		printf("\noutput=%f",o);
	}
	if((s==2)&&(d==7))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i*1.5;
		printf("\noutput=%f",o);
	}
	if((s==2)&&(d==8))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i*6.63;
		printf("\noutput=%f",o);
	}
	if((s==3)&&(d==1))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i/1.8;
		printf("\noutput=%f",o);
	}
	if((s==3)&&(d==2))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i*114.12;
		printf("\noutput=%f",o);
	}
	if((s==3)&&(d==3))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i;
		printf("\noutput=%f",o);
	}
	if((s==3)&&(d==4))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i/132.3;
		printf("\noutput=%f",o);
	}
	if((s==3)&&(d==5))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i/14.6;
		printf("\noutput=%f",o);
	}
	if((s==3)&&(d==6))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i/87.5;
		printf("\noutput=%f",o);
	}
	if((s==3)&&(d==7))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i/78.75;
		printf("\noutput=%f",o);
	}
	if((s==3)&&(d==8))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i/17.2;
		printf("\noutput=%f",o);
	}
	if((s==4)&&(d==1))
	{
		printf("\nenter input:-");
		scanf("\n%f",&i);
		o=i*75;
		printf("\noutput=%f",o);
	}
	if((s==4)&&(d==2))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i*1.15;
		printf("\noutput=%f",o);
	}
	if((s==4)&&(d==3))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=(i*132.3);
		printf("\noutput=%f",o);
	}
	if((s==4)&&(d==4))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i;
		printf("\noutput=%f",o);
	}
	if((s==4)&&(d==5))
	{
		printf("\nenter input:-");
		scanf("\n%f",&i);
		o=i/9;
		printf("\noutput=%f",o);
	}
	if((s==4)&&(d==6))
	{
		printf("\nenter input:-");
		scanf("\n%f",&i);
		o=i/1.51;
		printf("\noutput=%f",o);
	}
	if((s==4)&&(d==7))
	{
		printf("\nenter input:-");
		scanf("\n%f",&i);
		o=i*1.68;
		printf("\noutput=%f",o);
	}
	if((s==4)&&(d==8))
	{
		printf("\nenter input:-");
		scanf("\n%f",&i);
		o=i/7.69;
		printf("\noutput=%f",o);
	}
	if((s==5)&&(d==1))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=(i*8.3);
		printf("\noutput=%f",o);
	}
	if((s==5)&&(d==2))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i/7.8;
		printf("\noutput=%f",o);
	}
	if((s==5)&&(d==3))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i*14.6;
		printf("\noutput=%f",o);
	}
	if((s==5)&&(d==4))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i/9;
		printf("\noutput=%f",o);
	}
	if((s==5)&&(d==5))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i;
		printf("\noutput=%f",o);
	}
	if((s==5)&&(d==6))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i/6;
		printf("\noutput=%f",o);
	}
	if((s==5)&&(d==7))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i/5.38;
		printf("\noutput=%f",o);
	}
	if((s==5)&&(d==8))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i/1.18;
		printf("\noutput=%f",o);
	}
	if((s==6)&&(d==1))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i*49.6;
		printf("\noutput=%f",o);
	}
	if((s==6)&&(d==2))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i/1.3;
		printf("\noutput=%f",o);
	}
	if((s==6)&&(d==3))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i*87;
		printf("\noutput=%f",o);
	}
	if((s==6)&&(d==4))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i/1.5;
		printf("\noutput=%f",o);
	}
	if((s==6)&&(d==5))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i*6;
		printf("\noutput=%f",o);
	}
	if((s==6)&&(d==6))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i;
		printf("\noutput=%f",o);
	}
	if((s==6)&&(d==7))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i*1.11;
		printf("\noutput=%f",o);
	}
	if((s==6)&&(d==8))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i*5;
		printf("\noutput=%f",o);
	}
	if((s==7)&&(d==1))
	{
		printf("\nenter input:-");
		scanf("\n%f",&i);
		o=i*44.6;
		printf("\noutput=%f",o);
	}
	if((s==7)&&(d==2))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i/1.45;
		printf("\noutput=%f",o);
	}
	if((s==7)&&(d==3))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=(i*78.75);
		printf("\noutput=%f",o);
	}
	if((s==7)&&(d==4))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=(i/1.68);
		printf("\noutput=%f",o);
	}
	if((s==7)&&(d==5))
	{
		printf("\nenter input:-");
		scanf("\n%f",&i);
		o=i*5.38;
		printf("\noutput=%f",o);
	}
	if((s==7)&&(d==6))
	{
		printf("\nenter input:-");
		scanf("\n%f",&i);
		o=i/1.11;
		printf("\noutput=%f",o);
	}
	if((s==7)&&(d==7))
	{
		printf("\nenter input:-");
		scanf("\n%f",&i);
		o=i;
		printf("\noutput=%f",o);
	}
	if((s==7)&&(d==8))
	{
		printf("\nenter input:-");
		scanf("\n%f",&i);
		o=i*4.5;
		printf("\noutput=%f",o);
	}
	if((s==8)&&(d==1))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=(i*9.74);
		printf("\noutput=%f",o);
	}
	if((s==8)&&(d==2))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i/6.63;
		printf("\noutput=%f",o);
	}
	if((s==8)&&(d==3))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i*17.2;
		printf("\noutput=%f",o);
	}
	if((s==8)&&(d==4))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i/7.7;
		printf("\noutput=%f",o);
	}
	if((s==8)&&(d==5))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i*1.17;
		printf("\noutput=%f",o);
	}
	if((s==8)&&(d==6))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i/5;
		printf("\noutput=%f",o);
	}
	if((s==8)&&(d==7))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i/4.57;
		printf("\noutput=%f",o);
	}
	if((s==8)&&(d==8))
	{
		printf("\nenter input:-");
		scanf("%f",&i);
		o=i;
		printf("\noutput=%f",o);
	}

     getch();
}



int currency_convertor_out()
{
int o;
do
{
clrscr();
printf("\nenter a valid output currency type:-\n");
printf("\n1.RUPEE\n");
printf("\n2.USD(US Dollar)\n");
printf("\n3.YEN\n");
printf("\n4.EURO\n");
printf("\n5.HKD(Hong Kong Dollar)\n");
printf("\n6.Australian Dollar\n");
printf("\n7.New Zealand Dollar\n");
printf("\n8.Chinese YUAN\n");
printf("\n9.Previous Menu\n");
scanf("%d",&o);
}while(o>9);
return o;
}


int currency_convertor_in()
{
int i;
do
{
clrscr();
printf("\nenter a valid input currency type:-\n");
printf("\n1.RUPEE\n");
printf("\n2.USD(US Dollar)\n");
printf("\n3.YEN\n");
printf("\n4.EURO\n");
printf("\n5.HKD(Hong Kong Dollar)\n");
printf("\n6.Australian Dollar\n");
printf("\n7.New Zealand Dollar\n");
printf("\n8.Chinese YUAN\n");
printf("\n9.Previous Menu\n");
scanf("%d",&i);
}while(i>9);
return i;
}

